# Generated by Django 5.0.6 on 2024-09-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descroption',
            new_name='description',
        ),
    ]
